// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNNvBTRgFVwgnRLxFRk_nn8z9_41GXgVc',
    appId: '1:373291127267:web:08a6122ed1c58590c7d0d6',
    messagingSenderId: '373291127267',
    projectId: 'miranda-e21e3',
    authDomain: 'miranda-e21e3.firebaseapp.com',
    databaseURL: 'https://miranda-e21e3.firebaseio.com',
    storageBucket: 'miranda-e21e3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZQ7GmAgX_F6qE5U_aFDfInIQRDMsuitI',
    appId: '1:373291127267:android:e83b59835e88a1d7c7d0d6',
    messagingSenderId: '373291127267',
    projectId: 'miranda-e21e3',
    databaseURL: 'https://miranda-e21e3.firebaseio.com',
    storageBucket: 'miranda-e21e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmw_OZ6txWcpLJk_16kxYcpgE8wuGjBPc',
    appId: '1:373291127267:ios:4ec0488e02b219dec7d0d6',
    messagingSenderId: '373291127267',
    projectId: 'miranda-e21e3',
    databaseURL: 'https://miranda-e21e3.firebaseio.com',
    storageBucket: 'miranda-e21e3.appspot.com',
    androidClientId: '373291127267-875t544coc0j7ke8dlkore83rnio8q08.apps.googleusercontent.com',
    iosClientId: '373291127267-rv2kk785lt0m417u5df370vdcdtfor0b.apps.googleusercontent.com',
    iosBundleId: 'com.example.mpesaFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmw_OZ6txWcpLJk_16kxYcpgE8wuGjBPc',
    appId: '1:373291127267:ios:4ec0488e02b219dec7d0d6',
    messagingSenderId: '373291127267',
    projectId: 'miranda-e21e3',
    databaseURL: 'https://miranda-e21e3.firebaseio.com',
    storageBucket: 'miranda-e21e3.appspot.com',
    androidClientId: '373291127267-875t544coc0j7ke8dlkore83rnio8q08.apps.googleusercontent.com',
    iosClientId: '373291127267-rv2kk785lt0m417u5df370vdcdtfor0b.apps.googleusercontent.com',
    iosBundleId: 'com.example.mpesaFlutter',
  );
}
